config/routes.rb
Rails.application.routes.draw do
  resources :family_members
  resources :profiles, only: [:show, :update, :create, :new, :destroy, :edit]
  devise_for :users

   root 'home#index'

end

app/models/family_member.rb
class FamilyMember < ActiveRecord::Base
	self.table_name = 'family_member'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :family_members
	accepts_nested_attributes_for :family_members
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_one :profile

  after_create :create_profile
  
  def confirmation_required?
  	false
  end

  def create_profile
  	Profile.create(email: self.email)  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_action :set_family_member, only: [:show, :edit, :update, :destroy]
  before_action :set_profile_id
  # GET /family_members
  # GET /family_members.json
  def index
    @family_member = FamilyMember.where(profile_id: params[:profile_id])
  end

  # GET /family_members/1
  # GET /family_members/1.json
  def show
  end

  # GET /family_members/new
  def new
    @family_member = FamilyMember.new
  end

  # GET /family_members/1/edit
  def edit
  end

  # POST /family_members
  # POST /family_members.json
  def create
    @family_member = FamilyMember.new(family_member_params)

    respond_to do |format|
      if @family_member.save
        format.html { redirect_to @family_member, notice: 'Family member was successfully created.' }
        format.json { render :show, status: :created, location: @family_member }
      else
        format.html { render :new }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_members/1
  # PATCH/PUT /family_members/1.json
  def update
    respond_to do |format|
      if @family_member.update(family_member_params)
        format.html { redirect_to @family_member, notice: 'Family member was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_member }
      else
        format.html { render :edit }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_members/1
  # DELETE /family_members/1.json
  def destroy
    @family_member.destroy
    respond_to do |format|
      format.html { redirect_to family_members_url, notice: 'Family member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_member
      @family_member = FamilyMember.find(params[:id])
    end

    def set_profile_id
      params[:profile_id] = Profile.find_by(email: current_user.email).id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_member_params
      # params.fetch(:family_member, {})
      params[:family_member][:profile_id] = params[:profile_id]
      params.require(:family_member).permit(:name, :relationship, :blood_group, :age, :education, :email, :profile_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@profile = Profile.find_by(email: current_user.email) if current_user.present?
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find_by(email: current_user.email)
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :mobile, :city, :gender, :pin_code, :occupation, :blood_group, :address, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/family_members_helper.rb
module FamilyMembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/family_members/_form.html.erb
<%= simple_form_for(@family_member) do |f| %>
<%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :relationship %>
    <%= f.input :blood_group %>
    <%= f.input :age %>
    <%= f.input :education %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/family_members/edit.html.erb
<h1>Editing Family Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_member %> |
<%= link_to 'Back', family_members_path %>

app/views/family_members/index.html.erb
<div style="margin: 0 10%; padding: 2.5%; width: 80%; box-shadow: 0 0 8px #d6d6d6;">
<p id="notice"><%= notice %></p>
<h1>Listing Family Members</h1>
<br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Relatioinship</th>
      <th>Blood group</th>
      <th>Age</th>
      <th>Education</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @family_member.each do |family_members| %>
      <tr>
        <td><%= family_members.name %></td>
        <td><%= family_members.relationship %></td>
        <td><%= family_members.blood_group %></td>
        <td><%= family_members.age %></td>
        <td><%= family_members.education %></td>
        <td><%= family_members.email %></td>
        <td><%= link_to 'Show', family_members, {:class => 'btn '}  %></td>
        <td><%= link_to 'Edit', edit_family_member_path(family_members), {:class => 'btn '}  %></td>
        <td><%= link_to 'Destroy', family_members, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<span>
  <%= link_to 'New Family member', new_family_member_path,{:class => 'btn btn-default'}  %>
  <%= link_to 'Profile', edit_profile_path(params["profile_id"]), {:class => 'btn btn-default'}  %>
</span>
</div>
<style type="text/css">
table, td, th {
  border: 1px solid black;
}

table {
  border-collapse: collapse;
  width: 80%;
}
table, h1, span {
  margin: 0 10%;
}
th {
  height: 50px;
  padding: 2% 2%;
}
td {
  padding: 2% 2%;
}
</style>

app/views/family_members/new.html.erb
<div style="padding: 0 30%">
<h1>New Family Member</h1>

<%= render 'form' %>

<%= link_to 'Back', family_members_path %>
<%= link_to 'List Family', family_members_path(@profile),{:class => 'btn btn-default'} %>
</div>

app/views/family_members/show.html.erb
<div style="margin: 0 30%; padding: 3%; box-shadow: 0 0 8px #d6d6d6;">
<p id="notice"><%= notice %></p>
  <h1>Member Details</h1>
  <p>
    <strong>name:</strong>
    <%= @family_member[:name] %>
  </p>
  <p>
    <strong>Relatioinship:</strong>
    <%= @family_member[:relationship] %>
  </p>
  <p>
    <strong>Blood_group:</strong>
    <%= @family_member[:blood_group] %>
  </p>
  <p>
    <strong>Education:</strong>
    <%= @family_member[:education] %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= @family_member[:email] %>
  </p>
<%= link_to 'Edit', edit_family_member_path(@family_member), {:class => 'btn btn-default'} %> |
<%= link_to 'Back', family_members_path, {:class => 'btn btn-default'} %>
</div>

app/views/home/_footer.html.erb
<div class="container">
<div class="row">
<div class="footer col-md-12 table-bordered" id="foot">
<div id="gap"></div>
<center>  
<p>&copy; 2016 Rockfortreddiars.com<p>
  </center>
  </div>
  </div>
  </div>

  
 </body> 
</html>

app/views/home/_header.html.erb
<div class="container ">
  <div class="row">
    <div id="head"><a href="http://www.rockfortreddiars.com"><%= image_tag('header.jpg', style: "width:100%;") %></a></div>
  </div>
</div>
<div class="container">
  <div class="row">
    <nav class="navbar navbar-inverse">
    <div class="container-fluid table-bordered">
        <ul class="nav navbar-nav">
          <li ><a href="index.php">Home</a></li>
          <li><a href="members_list.php">Members List</a></li>
          <li><a href="gallery.php">Gallery</a></li> 
          <li><a href="about_us.php">About Us</a></li> 
          <li><a href="contact_us.php">Contact Us</a></li> 
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user.present? %>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
          <li><%= link_to 'Edit profile', edit_profile_path(@profile) %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</div>
<div class="container">
  <div class="row">
    <div id="slider" class="col-md-12 col-sm-6 col-md-8 table-bordered">
      <%= render "slider" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div id="flash" class="col-md-12 col-sm-6 col-md-8 table-bordered"></div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div id="container-left" class="col-md-2 table-bordered">
      <div id="gap"></div>
      <div class="list-group">
        <a href="#" class="list-group-item active">
          <p class="list-group-item-text">Quick Links</p>
        </a>
        <a href="#" class="list-group-item">
          <p class="list-group-item-text">Photo Gallery</p>
        </a>
        <a href="#" class="list-group-item">
          <p class="list-group-item-text">Events</p>
        </a>
        <a href="#" class="list-group-item">
          <p class="list-group-item-text">Members List</p>
        </a>
        <a href="#" class="list-group-item">
          <p class="list-group-item-text">News</p>
        </a>
      </div>
    </div>

app/views/home/_right_side_bar.html.erb
<div class="container-right col-md-3 table-bordered">

<div id="h-b-a-con"><h5 id="h-b-a">Birthday/Anniversary</h5></div>
<br><br><br><br><br><p>Under construction</p><br><br><br>
</div>
</div>
</div>

app/views/home/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel" >
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" id="imgcn">
      <%= image_tag('img1.jpg', id: 'slideimg') %>
    </div>

    <div class="item" id="imgcn">
      <%= image_tag('img2.jpg', id: 'slideimg') %>
    </div>

    <div class="item" id="imgcn">
      <%= image_tag('img3.jpg', id: 'slideimg') %>
    </div>

    <div class="item" id="imgcn">
      <%= image_tag('img4.jpg', id: 'slideimg') %>
    </div>
    <div class="item" id="imgcn">
      <%= image_tag('img5.jpg', id: 'slideimg') %>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/home/index.html.erb
<!-- header starts here -->
<%= render 'header' %>
<!-- header Ends here -->

<!--middle content starts here -->
<div id="" class="container-mid col-md-7 table-bordered">
<div id="gap"></div>
<p>Reddy (also transliterated as Reddi, Reddiar, Reddappa, Reddy) is a caste that originated in India, predominantly settled in Andhra Pradesh. They are classified as a forward caste. The origin of the Reddy has been linked to the Rashtrakutas, although opinions vary. At one time they were a warrior caste and later became feudal overlords and peasant proprietors. Historically they have been the land-owning aristocracy of the villages. Traditionally, they were a diverse community of merchants and cultivators. Their prowess as rulers and warriors is well documented in Telugu history.<a style="color:orange;" href="#">Continue Reading</a></p>

</div>
 <!--middle content ends here -->
 
 <!-- Right side bar starts here --> 
<%= render 'right_side_bar' %>
 
<!-- Right side bars Ends here --> 

<!-- Footer Area Starts here -->
<%= render 'footer' %>


<!-- Footer ends here -->

app/views/home/index.html1.erb
<% if current_user.present? %>
<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to 'Login', new_user_session_path %>
<%= link_to 'Sign up', new_user_registration_path %>
<% end %>
<%= @index %>

app/views/layouts/_footer.html.erb
<div class="container">
<div class="row">
<div class="footer col-md-12 table-bordered" id="foot">
<div id="gap"></div>
<center>  
<p>&copy; 2016 Rockfortreddiars.com<p>
  </center>
  </div>
  </div>
  </div>

  
 </body> 
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"> 
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Welcome to Rockfortreddiars.com</title>
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="styles/style.css" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
	<!-- Start VisualLightBox.com HEAD section -->
		<link rel="stylesheet" href="gallery_page1_files/vlb_files1/vlightbox1.css" type="text/css" />
		<link rel="stylesheet" href="gallery_page1_files/vlb_files1/visuallightbox.css" type="text/css" media="screen" />
<script src="gallery_page1_files/vlb_engine/jquery.min.js" type="text/javascript"></script>
		<script src="gallery_page1_files/vlb_engine/visuallightbox.js" type="text/javascript"></script>
  </head>
  <body>
  
  <div class="container ">
  <div class="row">
  <div id="head"><a href="http://www.rockfortreddiars.com"><img src="images/header.jpg" style="width:100%;" /></a></div></div></div>
  <div class="container">
  <div class="row">
  <nav class="navbar navbar-inverse">
  <div class="container-fluid table-bordered">
    
    <ul class="nav navbar-nav">
      <li ><a href="index.php">Home</a></li>
      <li><a href="members_list.php">Members List</a></li>
      <li><a href="gallery.php">Gallery</a></li> 
      <li><a href="about_us.php">About Us</a></li> 
      <li><a href="contact_us.php">Contact Us</a></li> 
    </ul>
	
    <ul class="nav navbar-nav navbar-right">
      <li><a href="signup.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
	
	<div class="col-sm-3 col-md-3 pull-right">
            <form class="navbar-form" role="search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search Members" name="q">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div> 
	
	</div>
</nav>
</div></div>
<div class="container">
<div class="row">
<div id="slider" class="col-md-12 col-sm-6 col-md-8 table-bordered">
<?php include('template/slider.php');?>

</div>
</div></div>
<div class="container">
<div class="row">
<div id="flash" class="col-md-12 col-sm-6 col-md-8 table-bordered"></div></div></div>

<div class="container">
<div class="row">
  <div id="container-left" class="col-md-2 table-bordered">
  
  <div id="gap"></div>
      <div class="list-group">
    <a href="#" class="list-group-item active">
      
      <p class="list-group-item-text">Quick Links</p>
    </a>
	
	<a href="#" class="list-group-item">
      
      <p class="list-group-item-text">Photo Gallery</p>
    </a>
	
	
    <a href="#" class="list-group-item">
      
      <p class="list-group-item-text">Events</p>
    </a>
    <a href="#" class="list-group-item">
      
      <p class="list-group-item-text">Members List</p>
    </a>
	<a href="#" class="list-group-item">
      
      <p class="list-group-item-text">News</p>
    </a>
	
	
  </div>
  
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ReddiyarCommunitySite</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'datap-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta charset="utf-8"> 
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Welcome to Rockfortreddiars.com</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="styles/style.css" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
	<!-- Start VisualLightBox.com HEAD section -->
	<link rel="stylesheet" href="gallery_page1_files/vlb_files1/vlightbox1.css" type="text/css" />
	<link rel="stylesheet" href="gallery_page1_files/vlb_files1/visuallightbox.css" type="text/css" media="screen" />
	<script src="gallery_page1_files/vlb_engine/jquery.min.js" type="text/javascript"></script>
	<script src="gallery_page1_files/vlb_engine/visuallightbox.js" type="text/javascript"></script>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :mobile %>
    <%= f.input :city %>
    <%= f.input :pin_code %>
    <%= f.input :occupation %>
    <%= f.input :blood_group %>
    <%= f.input :address %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div style="padding: 0 30%">
	<h1 class="text-center">Editing Profile</h1>

	<%= render 'form' %>
    <br />
    <br />
	<%= link_to 'Show', @profile, {:class => 'btn btn-default'} %>
	<%= link_to 'Home', root_path, {:class => 'btn btn-default'} %>
	<%= link_to 'List Family', family_members_path(@profile),{:class => 'btn btn-default'} %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>City</th>
      <th>Gender</th>
      <th>Pin code</th>
      <th>Occupation</th>
      <th>Blood group</th>
      <th>Address</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.mobile %></td>
        <td><%= profile.city %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.pin_code %></td>
        <td><%= profile.occupation %></td>
        <td><%= profile.blood_group %></td>
        <td><%= profile.address %></td>
        <td><%= profile.email %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div style="margin: 0 30%; padding: 3%; box-shadow: 0 0 8px #d6d6d6;">
  <p id="notice"><%= notice %></p>
  <h1>Profile Details</h1>
  <p>
    <strong>City:</strong>
    <%= @profile.city %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @profile.gender %>
  </p>

  <p>
    <strong>Pin code:</strong>
    <%= @profile.pin_code %>
  </p>

  <p>
    <strong>Occupation:</strong>
    <%= @profile.occupation %>
  </p>

  <p>
    <strong>Blood group:</strong>
    <%= @profile.blood_group %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @profile.address %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @profile.email %>
  </p>

  <%= link_to 'Edit', edit_profile_path(@profile), {:class => 'btn btn-default'} %>
  <%= link_to 'Home', root_path, {:class => 'btn btn-default'} %>
</div>